### ISSUE TITLE
Linux rJava Problem with initCoreNLP()

### ISSUE THREAD

**Issue by 13bzhang** [statsmaths/coreNLP#1]
Hi! My name is Baobao Zhang and I'm a PhD student at Yale. I studied with Jay actually. It's a small world. I trying to use the package on an Ubuntu E3 AWS server and I'm having problems with rJava.

The problem is that when I try to `initCoreNLP()`, I get this error message:

```r
Error in rJava::.jnew("edu.stanford.nlp.pipeline.StanfordCoreNLP", basename(path)) : 
  java.lang.UnsupportedClassVersionError: edu/stanford/nlp/pipeline/StanfordCoreNLP : Unsupported major.minor version 52.0
``` 

I have upgraded to Java 8.
```
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```
Here is my session info:
```r
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] coreNLP_0.4-1

loaded via a namespace (and not attached):
[1] plotrix_3.5-12 rJava_0.9-6    XML_3.98-1.1
```
One thing I have to say is that I had to install rJava by `sudo apt-get install r-cran-rjava` -- as that is a common solution. On my Macbook, I didn't get the error anymore after I updated to Java 8. If you could help me out, that would be awesome.

**Comment by 13bzhang** [comment]
Update: The problem appears to be with locating the Java library within the system. See the ugly solution in http://stackoverflow.com/questions/16438073/unable-to-install-rjava-in-r-3-0-in-ubuntu-13-04

**Comment by acholonu** [comment]
I am having the same problem.  The error still appears even after following the stackoverflow suggestion (i.e., I install jdk 8 and run  'sudo R CMD javareconf').  Any help would be appreciated.

**Comment by kbenoit** [comment]
I have the same problem with OS X.

```
KBsMBP15:analysis kbenoit$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

and from R:

```
> require(coreNLP)
Loading required package: coreNLP
> downloadCoreNLP()
trying URL 'http://nlp.stanford.edu/software//stanford-corenlp-full-2015-04-20.zip'
Content type 'application/zip' length 360824440 bytes (344.1 MB)
==================================================
downloaded 344.1 MB

[1] 0
> initCoreNLP()
Error in rJava::.jnew("edu.stanford.nlp.pipeline.StanfordCoreNLP", basename(path)) : 
 java.lang.UnsupportedClassVersionError: edu/stanford/nlp/pipeline/StanfordCoreNLP : Unsupported major.minor version 52.0

> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] coreNLP_0.4-1

loaded via a namespace (and not attached):
[1] tools_3.2.3   plotrix_3.6-1 rJava_0.9-8   XML_3.98-1.3 
```

**Comment by tpaskhalis** [comment]
I had the same issue on my Ubuntu 14.04.3 LTS machine and this solution worked for me. 

My understanding is that `sudo R CMD javareconf` from the above-mentioned Stackoverflow post uses Java installation which is located in `/usr/lib/jvm/default-java`. This seems to be a symlink to the first/only Java installation rather than the one which is set as the default by running `sudo update-alternatives --config java`, which can create a problem when you have multiple Java versions installed. It still pointed to `/usr/lib/jvm/java-1.7.0-openjdk-amd64` in my case. So, I manually edited the symlink with `sudo ln -sfn java-1.8.0-openjdk-amd64 default-java`, which resolved the problem for me. This solution is also not ideal as it might break other dependencies that rely on earlier Java versions but I cannot think of anything better than changing it back to `java-1.7.0-openjdk-amd64` when such an issue arises.

**Comment by void242** [comment]
I encountered the same problem which seems to be caused by rJava not referencing the correct JDK version. The below worked with reinstalling rJava and running the above javareconf command

http://paulklemm.com/zenf/blog/2015/02/20/run-rjava-with-rstudio-under-osx-10-dot-10/

**Comment by statsmaths** [comment]
The Stanford CoreNLP library only works with Java 8+. The problems mentioned in this thread are due to rJava not picking up the correct version of Java, even if you have installed the correct version. Unfortunately I cannot offer much help on this as it really has nothing directly to do with the package. One tip is that you can see the version of Java that is running from R using the following code snippet:
```{r}
library(rJava)
.jinit()
.jcall("java/lang/System","S","getProperty","java.version")
```

**Comment by filipedgb** [comment]
Has anyone found a solution to this problem yet? I keep having the same error 2 years later

**Comment by kbenoit** [comment]
Out of frustration, and the slow performance of CoreNLP, we're developing [**spacyr**](https://github.com/kbenoit/spacyr), an R interface to spaCy ("industrial strength natural language processing" Python library) from http://spacy.io.

Will submit to CRAN soon, as soon as we work out some of the installation issues on Windows.

**Comment by statsmaths** [comment]
As mentioned in the post from Feb 13, 2016, this is really an issue with rJava. It is very frustrating but ultimately unavoidable to figure out how to call Java 1.8 to work with CoreNLP. If you are continuing to have trouble I highly encourage commenting on the rJava (https://github.com/s-u/rJava) issues page; Simon Urbanek should be able to find the best solution.

@kebnoit: a wrapper to spaCy would be a very welcome addition to the landscape, though it is not a drop-in replacement for the CoreNLP library (it does not have fine grained POS tags, the co-reference and NER systems, nor does it work for nearly as many languages). cleanNLP does not get around the Java issues, but is greatly improved in terms of speed and easy of use, I would recommend looking at my newer package cleanNLP (https://github.com/statsmaths/cleanNLP). It would actually be really great to get cleanNLP to integrate with spacyr. Perhaps something we can bring up about in April.

**Comment by kbenoit** [comment]
Will do. Yes we really look forward to the chance to share experience and improve the various tagging and parsing packages. Maybe a common framework for structuring the return data?

We're putting our money on [**reticulate**](https://github.com/rstudio/reticulate) but it needs to get onto CRAN.

Installing the SpaCy and the language models on Windows is still difficult...

**Comment by JBGruber** [comment]
For Windows users who might wander off here by googling the error: 
1.  install most recent [Java version](http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html)
2. Set Java home in R to install folder of new Java version: Sys.setenv(JAVA_HOME='C:/Program Files/Java/jre1.8.0_121')

load coreNLP and enjoy :)
