### ISSUE TITLE
Syntax for parameterFile()

### ISSUE THREAD

**Issue by Gimperion** [statsmaths/coreNLP#10]
I've tried a number of permutations for inputting a path to a custom parameter file.  Nothing has worked thus far.  What is the right syntax?

Example:

> file.exists(file.path(getwd(), "core_nlp.params"))
> [1] TRUE
> initCoreNLP(parameterFile=file.path(getwd(), "core_nlp.params"))
> Error in rJava::.jnew("edu.stanford.nlp.pipeline.StanfordCoreNLP", basename(path)) : 
>   edu.stanford.nlp.io.RuntimeIOException: ERROR: cannot find properties file "core_nlp.params" in the classpath!

**Comment by lonihagen** [comment]
This is an rJava issue. You may want to download 64bit if you are using 64bit Rstudio.
