### ISSUE TITLE
nlp.stanford.edu website down?

### ISSUE THREAD

**Issue by arronlacey** [statsmaths/coreNLP#11]
Hi - I'm unable to download the zip file 

> http://nlp.stanford.edu/software/stanford-corenlp-full-2015-01-29.zip

because the website is down. has been for a few days now. does the github admin here have any control over the website?

is this file hosted elsewhere?

**Comment by lonihagen** [comment]
I was able to download today. Try it again.

**Comment by statsmaths** [comment]
I have not official association with the Stanford group, though the library does appear to be up now so I would just try again. If it becomes a common issue I could always host an alternative copy somewhere.

**Comment by arronlacey** [comment]
Thanks - was able to download today.

**Comment by shaleenx** [comment]
I was trying to download the pre-trained Glove embeddings from their website. Seems like it's down again https://www.isitdownrightnow.com/nlp.stanford.edu.html

**Comment by krishna-vicky96** [comment]
Hi,

I am not able to download glove vectors from http://nlp.stanford.edu/data/glove.6B.zip. I thinnk server is down, can anyone help me. I mean are there any other alternatives to get glove vectors.
