### ISSUE TITLE
getSentiment() errors

### ISSUE THREAD

**Issue by lonihagen** [statsmaths/coreNLP#12]
I've used your example code in statsmaths/coreNLP. As you can see below, I am getting NA's for sentiment results. Is this a bug or I'm making a mistake?  

Thanks.--Loni
===============================================
devtools::install_github("statsmaths/coreNLP")
coreNLP::downloadCoreNLP()
options(java.parameters = "-Xmx8000m")

library(coreNLP)
initCoreNLP()

catInHat = c("the sun did not shine.", "it was too wet to play.",
             "so we sat in the house all that cold, cold, wet day.")
output2 = annotateString(catInHat)
senti=getSentiment(output2)
> senti
  id sentimentValue sentiment
1  1             NA        NA
2  2             NA        NA
3  3             NA        NA
>

**Comment by statsmaths** [comment]
I finally tracked down this annoying bug, which I introduced in version 0.4-2, and it is now fixed. If you re-build the package from the github master branch the sentiment values should show up again. Please open a new issue if it persists on your end. Thanks!!!
