### ISSUE TITLE
getSentiment() function returning NA for sentimentvalue and sentiment

### ISSUE THREAD

**Issue by sivaram10** [statsmaths/coreNLP#15]
I'm tyring to extract sentiment from comments. I was able to use other functions such as annotateString and getTokens. But when I use getSentiment function, it is returning NA even for very simple sentences. 
![image](https://cloud.githubusercontent.com/assets/10365458/26359262/fa036e46-3fa2-11e7-915a-bda7f5560c9e.png)

**Comment by statsmaths** [comment]
How did you initialise the model? Could you please post a complete reproducible example.

**Comment by emilioxavier** [comment]
Hi
I experienced the same `getSentiment` result using the following commands. Please let me know if you need additional information.

Thank you!

```
R> library(coreNLP)
R> coreNLP::initCoreNLP(libLoc="/Users/emilio/software/stanford-corenlp-full-2016-10-31", type="english", mem="4g")
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Searching for resource: StanfordCoreNLP.properties ... found.
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator mention
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator coref
R> catInHat = c("the sun did not shine.", "it was too wet to play.", "so we sat in the house all that cold, cold, wet day.")
R> output = annotateString(catInHat)
R> getSentiment(output)
  id sentimentValue sentiment
1  1             NA        NA
2  2             NA        NA
3  3             NA        NA
```

**Comment by emilioxavier** [comment]
Sorry for the post. I reinstalled `coreNLP` from GitHub `devtools::install_github("statsmaths/coreNLP")`, restarted the R session, and re-ran the example. Everything works fine now. Results below...

```
R> library(coreNLP)
R> 
R> coreNLP::initCoreNLP(libLoc="/Users/emilio/software/stanford-corenlp-full-2016-10-31", type="english", mem="4g")
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Searching for resource: StanfordCoreNLP.properties ... found.
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[main] INFO edu.stanford.nlp.pipeline.TokenizerAnnotator - No tokenizer type provided. Defaulting to PTBTokenizer.
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
[main] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.5 sec].
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [0.9 sec].
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [1.2 sec].
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [0.4 sec].
[main] INFO edu.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse
[main] INFO edu.stanford.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.3 sec].
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator mention
[main] INFO edu.stanford.nlp.pipeline.MentionAnnotator - Using mention detector type: dependency
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator coref
[main] INFO edu.stanford.nlp.coref.statistical.SimpleLinearClassifier - Loading coref model edu/stanford/nlp/models/coref/statistical/ranking_model.ser.gz ... done [2.5 sec].
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator sentiment
R> catInHat = c("the sun did not shine.", "it was too wet to play.",
+ "so we sat in the house all that cold, cold, wet day.")
R> output = annotateString(catInHat)
R> getSentiment(output)
  id sentimentValue sentiment
1  1              1  Negative
2  2              1  Negative
3  3              1  Negative
```

**Comment by sivaram10** [comment]
coreNLP::initCoreNLP(libLoc="C:/Personal/Desktop/stanford-corenlp-full-2016-10-31", type="english", mem="12g")
sent <- c("John is very kind and he is very helpful.","Jack is a bad.")
output <- annotateString(sent)
getSentiment(output)

![image](https://cloud.githubusercontent.com/assets/10365458/26456726/f31c194e-413b-11e7-8e7c-39200cc047b8.png)

**Comment by emilioxavier** [comment]
Which version of `coreNLP` and R do you have installed? 
- What does `packageVersion("coreNLP")` return? Is it 0.4.2?
- What does `R.Version()$version.string` return?

Also, what if you set `mem="4g"`?

**Comment by statsmaths** [comment]
Yeah, the problem is that the CRAN version does not load the sentiment classifier by default. You can do it manually though by creating a parameter file and calling that as an option to `initCoreNLP`. The easiest solution is, as @emilioxavier mentions, to download the version on GitHub.

Also, I recommend checking out my other package: [**cleanNLP**](https://github.com/statsmaths/cleanNLP). It is a bit more user friendly but also allows for annotating text with the Stanford CoreNLP library.

**Comment by sivaram10** [comment]
coreNLP::initCoreNLP(libLoc="C:/Personal/Desktop/stanford-corenlp-full-2016-10-31", type="english", mem="4g")
> packageVersion("coreNLP")
[1] ‘0.4.2’
> R.Version()$version.string
[1] "R version 3.3.3 (2017-03-06)"
![image](https://cloud.githubusercontent.com/assets/10365458/26460928/4cd13804-4149-11e7-8c09-c9288b4d96aa.png)

I guess as statsmaths mentioned, by default, sentiment annotator is not loading. Please let me know how to specify sentiment annotator in parameter file and call it fro initCoreNLP function.

**Comment by statsmaths** [comment]
@sivaram10 Please just install the recent version from GitHub with this code:
```{r}
devtools::install_github("statsmaths/coreNLP")
```
And it should work fine.

**Comment by sivaram10** [comment]
Thanks @statsmaths. Its now working and I'll also check CleanNLP.

**Comment by GDawgg** [comment]
having the same issue even after running: devtools::install_github("statsmaths/coreNLP")

R version 3.6.1, RStudio version 1.2.5
