### ISSUE TITLE
Different outcomes between this coreNLP and online (http://nlp.stanford.edu:8080/parser/index.jsp)

### ISSUE THREAD

**Issue by seonho07** [statsmaths/coreNLP#20]
Hello,

I just got the dependency of the sentence "we have the self_contained plant_watering system"
Here is the outcome of R-version coreNLP.
as you can see below, the dobj of 'have' is 'the', which is not reasonable. 
  sentence       governor      dependent     type governorIdx dependentIdx govIndex depIndex
1        1           ROOT           have     root           0            2       NA        2
2        1           have             we    nsubj           2            1        2        1
3        1           have            the     dobj           2            3        2        3
4        1            the self_contained      acl           3            4        3        4
5        1         system plant_watering compound           6            5        6        5
6        1 self_contained         system     dobj           4            6        4        6

I tried the same sentence online( http://nlp.stanford.edu:8080/parser/index.jsp), which gave me
correct parsed outcome.

Could you please let me know how I can resolve this issue?

Thanks

**Comment by statsmaths** [comment]
The live version on the stanford site does not seem to be up at the moment, so I cannot directly test this. Differences in the two are likely due to different versions of CoreNLP (the package uses 3.6; online I believe uses 3.7). I would suggest migrating to the R package **cleanNLP**, which I also maintain, that seems to fix this issue for you as well.

**Comment by seonho07** [comment]
Hi;

 

As you suggested, I decided switch to cleanNLP.

Seems like cleanNLP can't generate correct POS in some cases.

Standford NLP provides a way to force tagging [https://nlp.stanford.edu/software/parser-faq.shtml#f]

 

Can I use this option through clean NLP?

 

Thanks

Seonho Hwang
