### ISSUE TITLE
Issue while using the annotateString finction

### ISSUE THREAD

**Issue by RaviTeja262** [statsmaths/coreNLP#3]
I am getting the followking issue while trying to annotate a string of text. i ham getting the same isse while passing a file as well. Is it a knows issue? I am using the 2015-12-09 version of stanfordNLP.

test2 <- "this is attest wiriteup to check the core NLP. i think its not working"
Ann_test <- annotateString(test2,format = "text")
Warning message:
In file.remove(tf) :
  cannot remove file 'C:\Users\******\AppData\Local\Temp\Rtmp6b7AYE\file25743ae128d', reason 'Permission denied'

**Comment by statsmaths** [comment]
I have not seen that bug before, but it seems like you are having permissions issues with your temporary directory. Is this a managed machine that may be locked down in some particularly aggressive way? Also, I recommend using the 2015-04-20 version of coreNLP with this package, as I have not tested it with the new version yet.
