### ISSUE TITLE
provide alternative URL/file for downloadCoreNLP()

### ISSUE THREAD

**Issue by dimpase** [statsmaths/coreNLP#4]
After installing coreNLP in the standard way, one is told to run `downloadCoreNLP()`

   > library(coreNLP)
   > initCoreNLP()
   Error in initCoreNLP() : 
        Please run downloadCoreNLP() in order to install required jar files.
   > 

which downloads 344Mb from (unmirrored!) Stanford stile http://nlp.stanford.edu
Now, if something goes wrong (e.g. the Java version is wrong, or Java is broken, or some other problem like this), one has to re-run `downloadCoreNLP()` and download the same 344Mb all over again. We struggled to install `coreNLP` on Windows (and then gave up and got it running in a Linux VM), and it the process had to run `downloadCoreNLP()` about 10 times, each of them took about 20-25 minutes, on a somewhat saturated college network in Oxford.

It would have been great if `downloadCoreNLP()` was able to get an alternative URL or file as an argument, this would have sped up things a lot.

**Comment by statsmaths** [comment]
I can certainly see why it could be useful to have an alternative for
grabbing the jar file. For example, grabbing it over a local repository
or even passing around a usb stick with the jar file on it. You can do
this manually by simply putting the unzipped file in the location specified
by the following:
```{r}
system.file("extdata",package="coreNLP")
```
I think allowing people to specify an alternative URL using the function
could get sloppy though. For example, would you allow users to specify
a different filename as well, or just a basepath? Can we assume the file
is zip compressed? Should the file be renamed? I instead just adding some
documentation to the `downloadCoreNLP` function to indicate alternatives.

**Comment by dimpase** [comment]
Anything that provides an alternative to waiting for ages for a slow download to finish is great, be it an implementation or a documentation.
