### ISSUE TITLE
how to set maxLength and MAX_ITEMS options via properties

### ISSUE THREAD

**Issue by yipcma** [statsmaths/coreNLP#7]
I'm trying to set MAX_ITEMS as i hit this warning pretty often:

`FactoredParser: exceeded MAX_ITEMS work limit [200000 items]; aborting.`

I put `MAX_ITEMS = 500000` on a new line in the .properties file but it doesn't seem to set the option.

Help much appreciated.

Thank you.

**Comment by statsmaths** [comment]
I can't seem to figure out how to do this via a properties file either. It would be possible to set this directly through the R function, though I'd like to avoid that when possible. You may get more information opening an issue on the actual coreNLP project's website.
